
name: Nepse Data Auto Scrape

on:
  push:
    branches:
      - main
  schedule:
    - cron: '20 16 * * *'  # Runs at 16:20 UTC (10:05 PM NPT)

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Execute Scraping Script
        run: |
          python scrape_nepse.py
      - name: Commit and Push Files
        run: |
           git config --local user.email "bhupen339473@gmail.com"
           git config --local user.name "bhupennn"        
           git add .
           git commit -am "Today's share data has been scrapped successfully!"
           git push origin main
